name: Tests

on:
  - push
  - pull_request

jobs:
  test:
    name: Unit and integration tests
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Setup dependencies
      run: |
          sudo apt-get install -qq lcov

    - name: Configure
      run: |
          autoreconf -i
          ./configure --enable-debug \
                      --enable-backtrace \
                      --enable-sanitize

    - name: Build
      run: |
          make -j$(nproc --all) CFLAGS=-O0

    - name: Test
      run: |
          make check CFLAGS=-O0 || (cat ./test-suite.log && false)

  linting:
    name: Linting
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - uses: DoozyX/clang-format-lint-action@v0.14
      with:
        source: 'src test'
        exclude: 'test/lib/munit.*'
        extensions: 'c,h'
        clangFormatVersion: 14
        style: file
